kind: Service
apiVersion: v1
metadata:
  name: ocp-echo-demo
  labels:
    app: ocp-echo-demo
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ocp-echo-demo
    name: ocp-echo-demo
  sessionAffinity: None

